# load libraries
library(shiny)
library(ggplot2)
library(tidyquant)
library(shinydashboard)
library(lubridate)

# load data
load("filteredData.RData")

stocks <- unique(filteredData$Symbol)
years <- unique(format(filteredData$Date, format="%Y"))

minYear <- 2011
maxYear <- 2018

ui <- dashboardPage(
    dashboardHeader(title="PSX stock app",
                    titleWidth = 350
                    ),
    dashboardSidebar(
        width = 350,
        sidebarMenu(
            
            selectInput(inputId="stockSelector", label="Select The stock", choices=stocks, selected="OGDC"),
            sliderInput("yearSelector", "Years for price range", minYear, maxYear, value = c(minYear, maxYear))
            )
        ),
    dashboardBody(
        tags$head(
            tags$link(rel = "stylesheet", type = "text/css", href = "style.css")
        ),
        fluidRow(
            br(),
            box(
                h2("Hub Power Company Limited"),
                p("Hub Power Company Limited (HUBCO) is a Pakistani independent power producing company based in Hub, Lasbela District, Balochistan, Pakistan."),
                p("nIts 1,292 MW plant is located 60 km from Karachi in Hub. The electricity at HUBCO is generated by four 323 megawatt oil-fired units that are supplied by a 78 km long pipeline from Pakistan State Oil."),
                p("It consists of four generating units, each unit has capacity of 323 MW gross output, with an oil-fired single re-heat boiler and tandem compound and two cylinder condensing steam turbines directly coupled to a hydrogen cooled generator.")
            ),            
            column(width = 6,  box(title = "Stock Graph", width = NULL, solidHeader = FALSE, plotOutput("stockPlot")))
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
    stockData <- reactive({
        filteredData <- filteredData[filteredData$Symbol == input$stockSelector,]
        filteredData[((year(filteredData$Date) >= input$yearSelector[1]) & (year(filteredData$Date) <= input$yearSelector[2])),]
    })
    
   output$stockPlot <- renderPlot({
       ggplot(stockData(), aes(x = Date, y = Close)) +
           geom_line() +

           labs(y = "Closing Price", x = "Time") +
           theme_tq() +
           theme(text = element_text(size=17),
                 plot.background = element_rect(fill = "#F6F4E8"),
                 panel.background = element_rect(fill = "#F6F4E8"))

   })
}

# Run the application
shinyApp(ui = ui, server = server)
